# Generated by Django 3.2.5 on 2021-07-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='type',
            field=models.CharField(choices=[('Interior design', 'Interior design'), ('Product design', 'Product design'), ('3D visualizations', '3D visualizations'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
