# Generated by Django 3.2.5 on 2021-07-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_design_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs'),
        ),
    ]
