# Generated by Django 3.2.5 on 2021-07-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_alter_design_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='type',
            field=models.CharField(choices=[('interior', 'Interior design'), ('product', 'Product design'), ('3d', '3D visualizations'), ('other', 'Other')], default='Other', max_length=20),
        ),
    ]
