# Generated by Django 3.2.5 on 2021-07-25 16:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_alter_design_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(25)]),
        ),
    ]
